<h1>Importando Bibliotecas e CSV

In [1]:
import pandas as pd
from surprise import KNNBasic
from surprise import Dataset
from surprise import Reader

In [2]:
cd /Users/Gabriel/Datasets/GoGame

C:\Users\Gabriel\Datasets\GoGame

In [3]:
df = pd.read_csv("tbl_users_games.csv")

<EDA>

<h1>Ajustando os Dados

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301406 entries, 0 to 301405
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           301406 non-null  int64
 1   user_id      301406 non-null  int64
 2   game_id      301406 non-null  int64
 3   platform_id  301406 non-null  int64
 4   network_id   0 non-null       float64
 5   is_favorite  301406 non-null  int64
 6   status_id    301406 non-null  int64
dtypes: float64(1), int64(6)
memory usage: 16.1 MB

In [5]:
df.shape

(301406, 7)

In [6]:
df.columns

Index(['id', 'user_id', 'game_id', 'platform_id', 'network_id', 'is_favorite',
       'status_id'],
      dtype='object')

In [7]:
gogame = df.drop(columns=['id', 'platform_id', 'network_id', 'status_id'])

In [8]:
gogame.columns

Index(['user_id', 'game_id', 'is_favorite'], dtype='object')

In [15]:
#Alterar o n para o algoritmo utilizar mais dados da base
gogame_fr = gogame.sample(n=3000, random_state=42)

In [16]:
gogame_fr.head(60)

        user_id  game_id  is_favorite
229202    31834    48931            0
12116      2108    30091            0
140508      313    94664            0
40991      6578    77651            0
37333      6016     6661            0
212087    30374    97871            0
143281    22164    99181            0
72272     10292    48931            0
72763     11545    91701            0
300771    70642   113091            0
264499    40848    94883            0
273284    49757   109843            0
11490      2015    19641            0
236435    32614    94002            0
235305    32450    27601            0
137474    21372    61021            0
164448    23891    47261            0
169805    24902    72481            0
221743     2679    60011            0
66721     10452    28461            0
214874    30603    98408            0
220410    30960    43281            0
129439     5745     2641            0
24866      4246    16151            0
50441      8058    14191            0
222297    30718    28441            0
294676    65770   109280            0
224197    31338    47781            0
126961    20039    36481            0
283936    55205    40651            0
190691    27543     2971            0
210783    30224    37921            0
105677    16829    24621            0
93350     14882     6691            0
292524    63932   112756            0
50227      8023    94773            0
20550      3588    54241            0
73456     11327    81041            0
192680    27827    99972            0
49327      7894    91031            0
122521    19242    95835            0
139501    21497    37981            0
211176    30272    98145            0
275199    30889   103342            0
2351        319    93777            0
182844    26579    84771            0
96690     15342    46731            0
696          47    85401            0
52696      8359    93541            0
51515      8226    81911            0
273520    30889   105803            0
256142    37542   103733            0
71423     11323    93621            0
88986     14250    70121            1
177649    25915    96696            0
113540    18031    10552            0
128894    20101    74731            0
83925     13466    39112            0
55584      8856    43271            0
211654    30278    51781            0

<h1>Algoritmo de Recomendação

In [17]:
rating_dic = {'user' : gogame_fr['user_id'],
             'game' : gogame_fr['game_id'],
             'favorite': gogame_fr['is_favorite']}

In [18]:
def FriendRecommender (user):
    df = pd.DataFrame (rating_dic)
    reader = Reader(rating_scale=(0,1))
    data = Dataset.load_from_df(df[['user', 'game', 'favorite']], reader)
    trainset = data.build_full_trainset()
    sim_options = {'name' : 'cosine',
                  'user_based' : True}
    
    algo = KNNBasic(sim_options)
    algo.fit(trainset)
    
    uid = trainset.to_inner_uid(user) 
    pred = algo.get_neighbors(uid, 3)
    
    for i in pred:
        print(trainset.to_raw_uid(i))

In [20]:
#Alterar o user_id para gerar a lista de recomendações
FriendRecommender(14250)

Computing the msd similarity matrix...
Done computing similarity matrix.
6069
2252
25915